#!/usr/bin/env python3
"""Cross-link notes and code, in both directions.

Forward: each note gets a managed `## Linked code` block listing the symbols it
names, with file and line.

Backward: `CODE-INDEX.md` lists, per symbol, the notes that mention it. This is
the direction that is usually missing and usually wanted — *what has been said
about this function* is a question nobody can answer from the code alone.

The matching is LEXICAL. It finds identifiers a note actually spells out. It
will not know that "the enrichment channel" means `enrich_records()` unless the
note says so.

Usage:
    python3 link.py --vault vault/ --symbols symbols.json
    python3 link.py --vault vault/ --symbols symbols.json --check
    python3 link.py --vault vault/ --symbols symbols.json --explain
"""

from __future__ import annotations

import argparse
import collections
import json
import os
import re
import sys
from typing import Dict, List, Tuple

#: Names too common to be evidence of anything. A note mentioning "data" should
#: not acquire a link to every table called `data`. Extend with --stopwords.
_DEFAULT_STOP = {
    "data", "value", "values", "result", "results", "config", "settings",
    "status", "content", "context", "request", "response", "record", "records",
    "session", "message", "options", "params", "output", "input", "index",
    "update", "create", "delete", "select", "insert", "filter", "process",
    "handler", "manager", "service", "client", "server", "public", "private",
    "string", "number", "object", "array", "table", "column", "schema",
    "severity", "sections", "related", "title", "notes",
}

_SNAKE = re.compile(r"\b(_?[a-z][a-z0-9_]*)\b")
_CAMEL = re.compile(r"\b([A-Z][A-Za-z0-9]+)\b")
_CODE_SPAN = re.compile(r"`([^`\n]{2,80})`")

_FORWARD_HEADING = "## Linked code"
_BLOCK_START = "<!-- tracelink:linked-code:start -->"
_BLOCK_END = "<!-- tracelink:linked-code:end -->"

_FRONTMATTER = re.compile(r"\A---\n.*?\n---\n", re.S)
_MANAGED = re.compile(
    re.escape(_BLOCK_START) + r".*?" + re.escape(_BLOCK_END) + r"\n*", re.S)
#: blocks written before the markers existed, so old vaults heal on first run
_LEGACY_BLOCK = re.compile(r"^## Linked code\n\n(?:- .*\n)*\n?", re.M)
#: `Related:` is generated by split.py and must not be matched either
_GENERATED_LINE = re.compile(r"^Related: .*$", re.M)



_FM_BLOCK = re.compile(r"\A---\n(.*?)\n---\n", re.S)
_OWNED = re.compile(r"^tracelink_schema:\s*1\s*$", re.M)


def is_owned_note(text: str) -> bool:
    """Ownership lives in the frontmatter, not anywhere in the file.

    A substring search made a hand-written note that merely MENTIONS
    `tracelink_schema:` look owned — and therefore rewritable. The guarantee is
    only worth stating if the marker is structural.
    """
    m = _FM_BLOCK.match(text)
    return bool(m and _OWNED.search(m.group(1)))


def matchable(text: str) -> str:
    """The part of a note a human actually wrote.

    tracelink must never read its own output, and this is the single most
    important line in the tool.

    Frontmatter carries `status` and `severity`. The managed block carries the
    symbols found on the previous run. Scanning either makes the tool match
    itself: the first published demo linked both example notes to `severity` —
    a function inside `split.py` — and reported "2/2 notes linked" as though it
    had found the symbols named in the findings. Every statistic downstream was
    then formally correct and substantively false.

    It also makes links immortal. A symbol removed from the prose survives
    forever, because the next run rediscovers it in the block written by the
    last one.
    """
    text = _FRONTMATTER.sub("", text)
    text = _MANAGED.sub("", text)
    text = _LEGACY_BLOCK.sub("", text)
    text = _GENERATED_LINE.sub("", text)
    return text


def strip_managed(text: str) -> str:
    """Remove the managed block, leaving everything a human wrote."""
    return _LEGACY_BLOCK.sub("", _MANAGED.sub("", text))


def candidates(text: str, symbols: Dict[str, str], min_len: int,
               stop: set) -> List[Tuple[str, str]]:
    """Symbols the note names, ranked by how deliberate the reference is.

    A name inside backticks is a decision; a bare word of the same spelling may
    be prose. Ranking before truncation matters — capping an alphabetically
    sorted list throws away the strongest evidence for the weakest.
    """
    ranked: Dict[str, str] = {}
    for span in _CODE_SPAN.findall(text):
        token = span.strip().rstrip("()").lstrip(".")
        if token in symbols:
            ranked[token] = "inline-code"
    for m in _SNAKE.findall(text):
        if m in ranked or m in stop or len(m) < min_len:
            continue
        if m in symbols:
            ranked[m] = "identifier"
    for m in _CAMEL.findall(text):
        if m in ranked or m.lower() in stop or len(m) < min_len:
            continue
        if m in symbols:
            ranked[m] = "identifier"
    order = {"inline-code": 0, "identifier": 1}
    return sorted(ranked.items(), key=lambda kv: (order[kv[1]], kv[0]))



def normalise(symbols: dict) -> dict:
    """Accept v1 (name -> "path:line") and v2 (name -> [locations]).

    Everything downstream sees a list, so ambiguity is representable rather than
    silently collapsed.
    """
    out = {}
    for name, val in symbols.items():
        if isinstance(val, list):
            out[name] = val
        else:
            txt = str(val)
            path, _, line = txt.rpartition(":")
            out[name] = [{"path": path or txt,
                          "line": line.lstrip("L") if path else None,
                          "kind": "", "qualified_name": name}]
    return out


def fmt(loc: dict) -> str:
    return f"{loc['path']}:L{loc['line']}" if loc.get("line") else str(loc["path"])


def disambiguate(name: str, locations: list, text: str, overrides: dict):
    """Pick a location only when the evidence points at exactly one.

    Two candidates supported by the note are not a tie to break — they are the
    author naming both. Returning the first was the same defect as v1 resolving
    duplicates by filesystem order, moved one level up.

    An explicit override may win over textual evidence because it is a
    structured decision. A qualified name and a path are both authorial
    evidence of the same weight: when they disagree, that is a conflict to
    report, not a precedence to invent.
    """
    if name in overrides:
        want = overrides[name]
        for loc in locations:
            if want in (loc.get("qualified_name"), loc["path"], fmt(loc)):
                return loc, "frontmatter-override"
        return None, "override-unmatched"
    if len(locations) == 1:
        return locations[0], "unique"

    by_qualified = [l for l in locations
                    if l.get("qualified_name") and l["qualified_name"] != name
                    and l["qualified_name"] in text]
    by_path = [l for l in locations if l["path"] in text]

    if len(by_qualified) > 1:
        return None, "multiple-qualified-names"
    if len(by_path) > 1:
        return None, "multiple-paths-in-note"
    if by_qualified and by_path and by_qualified[0] is not by_path[0]:
        return None, "qualified-name-and-path-disagree"
    if len(by_qualified) == 1:
        return by_qualified[0], "qualified-name"
    if len(by_path) == 1:
        return by_path[0], "path-in-note"
    return None, "ambiguous"


_OVERRIDE = re.compile(r"^\s*tracelink:\s*$\n((?:\s+\w[\w.]*:\s*\S+\s*\n)+)", re.M)


def read_overrides(text: str) -> dict:
    """`tracelink:` mapping in the frontmatter, when the author has decided."""
    m = _OVERRIDE.search(text[:2000])
    if not m:
        return {}
    out = {}
    for line in m.group(1).splitlines():
        if ":" in line:
            k, _, v = line.strip().partition(":")
            if k and v.strip() and k != "symbols":
                out[k.strip()] = v.strip()
    return out


def render_block(links, symbols) -> str:
    body = "\n".join(f"- `{name}` — {fmt(loc)}" for name, loc, _why in links)
    return f"{_BLOCK_START}\n{_FORWARD_HEADING}\n\n{body}\n{_BLOCK_END}\n"


def apply_block(text: str, links: List[Tuple[str, str]],
                symbols: Dict[str, str]) -> str:
    """Always rebuilt from the current match; removed when nothing matches.

    The previous implementation only ran when there were hits, so a note whose
    last symbol left the prose kept its stale block indefinitely.
    """
    stripped = strip_managed(text)
    if not links:
        return stripped
    block = render_block(links, symbols)
    if stripped.startswith("---"):
        end = stripped.find("\n---", 3)
        cut = stripped.find("\n", end + 1) + 1 if end != -1 else 0
        return stripped[:cut] + "\n" + block + stripped[cut:]
    return block + "\n" + stripped


def write_atomic(path: str, content: str) -> None:
    tmp = path + ".tracelink.tmp"
    with open(tmp, "w") as fh:
        fh.write(content)
    os.replace(tmp, path)



# --------------------------------------------------------------------------- #
# freshness — is this index still about the repository in front of us?
# --------------------------------------------------------------------------- #

class Freshness:
    """Four states, because a boolean cannot express "I do not know".

    The distinctions that matter, each learned from a way of being wrong:

        same commit        != same files      (the working tree can be dirty)
        clean repository   != same commit
        provenance present != freshness verified
        fresh              != complete
        unknown            != fresh

    `stale` requires positive evidence of divergence. `fresh` requires positive
    evidence of correspondence. Everything else is `unknown`, and `unknown` is
    reported as such rather than rounded to the comfortable side.
    """

    def __init__(self, status, reasons=None, **fields):
        self.status = status
        self.reasons = reasons or []
        self.__dict__.update(fields)

    def as_dict(self):
        d = {k: v for k, v in self.__dict__.items() if k != "reasons"}
        d["reasons"] = self.reasons
        return d


def verify_freshness(payload, repo, index_path=None):
    """Compare an index against the repository it claims to describe."""
    import sys as _s
    _s.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    try:
        from symbols import fingerprint as _fp, repo_state as _rs
    except Exception:  # noqa: BLE001
        return Freshness("unknown", ["indexer-unavailable"])

    # A v1 index is a bare mapping with no envelope. It must stay loadable —
    # rejecting it as invalid would break every vault written before v2 and
    # punish the user for our schema history.
    if "symbols" not in payload:
        if payload and all(isinstance(v, (str, list)) for v in payload.values()):
            return Freshness("unknown", ["legacy-index-without-provenance"],
                             partial=False, indexed_commit=None, current_commit=None)
        return Freshness("invalid", ["not-a-symbol-index"])
    if not isinstance(payload.get("symbols"), dict):
        return Freshness("invalid", ["symbols-not-a-mapping"])

    indexing = payload.get("indexing") or {}
    partial = bool(indexing.get("partial"))

    repo_meta = payload.get("repository") or {}
    idx_commit = repo_meta.get("commit") or payload.get("repo_commit")
    idx_dirty = repo_meta.get("dirty")
    idx_fp = repo_meta.get("fingerprint")

    if idx_commit is None and idx_fp is None:
        return Freshness("unknown", ["legacy-index-without-provenance"],
                         partial=partial, indexed_commit=None, current_commit=None)

    _vcs, cur_commit, cur_dirty = _rs(os.path.realpath(repo))
    common = dict(partial=partial, indexed_commit=idx_commit,
                  current_commit=cur_commit, indexed_dirty=idx_dirty,
                  current_dirty=cur_dirty, indexed_fingerprint=idx_fp)

    # The fingerprint is the strongest evidence: it covers uncommitted work and
    # repositories with no VCS at all, so it is checked first and it decides.
    if idx_fp:
        cur_fp, _n, _w = _fp(os.path.realpath(repo), ignore_files=[index_path] if index_path else None)
        common["current_fingerprint"] = cur_fp
        if cur_fp == idx_fp:
            return Freshness("fresh", ["fingerprint-match"], **common)
        return Freshness("stale", ["fingerprint-mismatch"], **common)

    # v2 index: a commit and nothing else. It can prove divergence but not
    # correspondence, because the working tree is invisible to it.
    if cur_commit is None:
        return Freshness("unknown", ["git-unavailable-or-not-a-repository"], **common)
    if idx_commit != cur_commit:
        return Freshness("stale", ["commit-mismatch"], **common)
    if cur_dirty:
        return Freshness("stale", ["working-tree-modified"], **common)
    return Freshness("unknown", ["commit-match-without-fingerprint"], **common)


def render_freshness(f, fmt="text"):
    if fmt == "json":
        return None
    lines = [f"index_freshness:   {f.status}"]
    for r in f.reasons:
        lines.append(f"reason:            {r}")
    for label, attr in (("indexed_commit", "indexed_commit"),
                        ("current_commit", "current_commit")):
        v = getattr(f, attr, None)
        if v:
            lines.append(f"{label}:    {v[:12]}")
    if getattr(f, "partial", False):
        lines.append("index_completeness: partial — it does not cover the whole repository")
    if f.status == "stale":
        lines.append("")
        lines.append("Run the symbol indexer again before trusting generated links.")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description="Cross-link notes and code.")
    ap.add_argument("--vault", required=True)
    ap.add_argument("--symbols", required=True)
    ap.add_argument("--max-links", type=int, default=8,
                    help="cap per note, applied AFTER ranking (default 8)")
    ap.add_argument("--min-len", type=int, default=7,
                    help="minimum identifier length outside backticks (default 7)")
    ap.add_argument("--stopwords", default="", help="comma-separated extra names to ignore")
    ap.add_argument("--check", action="store_true",
                    help="report what would change, write nothing; exit 1 if stale")
    ap.add_argument("--explain", action="store_true",
                    help="print why each link was made")
    ap.add_argument("--repo", default=".",
                    help="repository the index claims to describe (default .)")
    ap.add_argument("--freshness", choices=["warn", "require", "ignore"], default="warn",
                    help="what to do when the index no longer matches the repo")
    ap.add_argument("--require-fresh-index", action="store_true",
                    help="alias for --freshness require")
    ap.add_argument("--allow-partial-index", action="store_true",
                    help="accept an index whose scan did not complete")
    ap.add_argument("--format", choices=["text", "json"], default="text")
    args = ap.parse_args()

    with open(args.symbols) as fh:
        payload = json.load(fh)
    mode = "require" if args.require_fresh_index else args.freshness
    fresh = None
    if mode != "ignore":
        fresh = verify_freshness(payload, args.repo, args.symbols)
        if args.format == "text":
            print(render_freshness(fresh))
            print()
        # The diagnostic is emitted even when we refuse to link. A CI consumer
        # asking for JSON and receiving prose on stderr has been given nothing
        # it can act on — the machine-readable promise has to hold on the
        # failure path especially, since that is the path it exists for.
        refusal = None
        if fresh.status == "invalid":
            refusal = ("invalid-index", 2)
        elif mode == "require":
            if fresh.status in ("stale", "unknown"):
                refusal = (f"freshness-{fresh.status}", 1)
            elif getattr(fresh, "partial", False) and not args.allow_partial_index:
                refusal = ("partial-index", 1)
        if refusal:
            reason, code = refusal
            if args.format == "json":
                print(json.dumps({"ok": False, "exit_reason": reason,
                                  "freshness": fresh.as_dict(), "linking": None}, indent=1))
            else:
                print(f"refusing to link: {reason}", file=sys.stderr)
                if fresh.status == "stale":
                    print("\nSuggested action:\n  python3 scripts/symbols.py "
                          f"--repo {args.repo} --out {args.symbols}", file=sys.stderr)
            return code

    symbols = normalise(payload.get("symbols") or payload)
    stop = set(_DEFAULT_STOP) | {s.strip() for s in args.stopwords.split(",") if s.strip()}

    # RES-OWNERSHIP: only notes tracelink generated. Pointing --vault at a
    # directory of hand-written markdown must never rewrite it.
    notes, skipped = [], 0
    for p in sorted(os.listdir(args.vault)):
        if not p.endswith(".md") or p in ("INDEX.md", "CODE-INDEX.md"):
            continue
        if is_owned_note(open(os.path.join(args.vault, p), errors="replace").read()):
            notes.append(p)
        else:
            skipped += 1
    if skipped:
        print(f"warning: skipped {skipped} markdown file(s) without tracelink_schema")
    if not notes:
        print(f"no notes in {args.vault}")
        return 1

    backward: Dict[str, List[str]] = collections.defaultdict(list)
    scanned = with_matches = modified = total_links = ambiguous = 0

    for name in notes:
        path = os.path.join(args.vault, name)
        text = open(path, errors="replace").read()
        scanned += 1
        body = matchable(text)
        overrides = read_overrides(text)
        links, note_ambiguous = [], []
        for sym, why in candidates(body, symbols, args.min_len, stop):
            loc, how = disambiguate(sym, symbols[sym], body, overrides)
            if loc is None:
                note_ambiguous.append((sym, how))
                continue
            links.append((sym, loc, f"{why}/{how}"))
        links = links[: args.max_links]
        ambiguous += len(note_ambiguous)
        for sym, how in note_ambiguous:
            print(f"AMBIGUOUS {sym} in {name} ({how})")
            for loc in symbols[sym]:
                print(f"  - {fmt(loc)}")
        if links:
            with_matches += 1
            total_links += len(links)
        new = apply_block(text, links, symbols)
        if new != text:
            modified += 1
            if not args.check:
                write_atomic(path, new)
        stem = os.path.splitext(name)[0]
        for sym, loc, why in links:
            backward[sym].append((stem, fmt(loc)))
            if args.explain:
                print(f"{stem} -> {sym}\n    reason: {why}\n    destination: {fmt(loc)}")

    lines = [
        "# Code index — which notes mention which symbol",
        "",
        f"Generated from `{os.path.basename(args.symbols)}` "
        f"(backend: {payload.get('backend', 'unknown')}).",
        "",
        "Matching is lexical: it finds symbols the notes actually spell out.",
        "Frontmatter and generated blocks are excluded, so tracelink never",
        "matches its own output.",
        "",
        "| symbol | location | notes |",
        "|---|---|---|",
    ]
    for sym in sorted(backward, key=lambda s: (-len({n for n, _ in backward[s]}), s)):
        refs = " ".join(f"[[{n}]]" for n in sorted({n for n, _ in backward[sym]}))
        loc = sorted({l for _, l in backward[sym]})[0].replace("|", r"\|")
        lines.append(f"| `{sym}` | {loc} | {refs} |")
    index_text = "\n".join(lines) + "\n"

    index_path = os.path.join(args.vault, "CODE-INDEX.md")
    index_stale = (not os.path.exists(index_path)
                   or open(index_path, errors="replace").read() != index_text)
    if index_stale and not args.check:
        write_atomic(index_path, index_text)

    if args.format == "json":
        print(json.dumps({
            "ok": not (args.check and (modified or index_stale)),
            "exit_reason": None,
            "freshness": fresh.as_dict() if fresh else None,
            "linking": {"notes_scanned": scanned, "notes_with_matches": with_matches,
                        "notes_modified": modified, "symbols_linked": total_links,
                        "distinct_symbols": len(backward), "ambiguous_matches": ambiguous},
        }, indent=1))
        return 1 if (args.check and (modified or index_stale)) else 0
    print(f"notes_scanned:      {scanned}")
    print(f"notes_with_matches: {with_matches}")
    print(f"notes_modified:     {modified}")
    print(f"symbols_linked:     {total_links}")
    print(f"distinct_symbols:   {len(backward)}")
    print(f"ambiguous_matches:  {ambiguous}")
    stale_note = payload.get("repo_commit")
    if stale_note:
        print(f"index_commit:       {stale_note[:12]}")
    if args.check:
        stale = modified + (1 if index_stale else 0)
        print(f"check: {stale} file(s) would change")
        return 1 if stale else 0
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
