#!/usr/bin/env python3
"""Cross-link notes and code, in both directions.

Forward: each note gets a managed `## Linked code` block listing the symbols it
names, with file and line.

Backward: `CODE-INDEX.md` lists, per symbol, the notes that mention it. This is
the direction that is usually missing and usually wanted — *what has been said
about this function* is a question nobody can answer from the code alone.

The matching is LEXICAL. It finds identifiers a note actually spells out. It
will not know that "the enrichment channel" means `enrich_records()` unless the
note says so.

Usage:
    python3 link.py --vault vault/ --symbols symbols.json
    python3 link.py --vault vault/ --symbols symbols.json --check
    python3 link.py --vault vault/ --symbols symbols.json --explain
"""

from __future__ import annotations

import argparse
import collections
import json
import os
import re
from typing import Dict, List, Tuple

#: Names too common to be evidence of anything. A note mentioning "data" should
#: not acquire a link to every table called `data`. Extend with --stopwords.
_DEFAULT_STOP = {
    "data", "value", "values", "result", "results", "config", "settings",
    "status", "content", "context", "request", "response", "record", "records",
    "session", "message", "options", "params", "output", "input", "index",
    "update", "create", "delete", "select", "insert", "filter", "process",
    "handler", "manager", "service", "client", "server", "public", "private",
    "string", "number", "object", "array", "table", "column", "schema",
    "severity", "sections", "related", "title", "notes",
}

_SNAKE = re.compile(r"\b(_?[a-z][a-z0-9_]*)\b")
_CAMEL = re.compile(r"\b([A-Z][A-Za-z0-9]+)\b")
_CODE_SPAN = re.compile(r"`([^`\n]{2,80})`")

_FORWARD_HEADING = "## Linked code"
_BLOCK_START = "<!-- tracelink:linked-code:start -->"
_BLOCK_END = "<!-- tracelink:linked-code:end -->"

_FRONTMATTER = re.compile(r"\A---\n.*?\n---\n", re.S)
_MANAGED = re.compile(
    re.escape(_BLOCK_START) + r".*?" + re.escape(_BLOCK_END) + r"\n*", re.S)
#: blocks written before the markers existed, so old vaults heal on first run
_LEGACY_BLOCK = re.compile(r"^## Linked code\n\n(?:- .*\n)*\n?", re.M)
#: `Related:` is generated by split.py and must not be matched either
_GENERATED_LINE = re.compile(r"^Related: .*$", re.M)


def matchable(text: str) -> str:
    """The part of a note a human actually wrote.

    tracelink must never read its own output, and this is the single most
    important line in the tool.

    Frontmatter carries `status` and `severity`. The managed block carries the
    symbols found on the previous run. Scanning either makes the tool match
    itself: the first published demo linked both example notes to `severity` —
    a function inside `split.py` — and reported "2/2 notes linked" as though it
    had found the symbols named in the findings. Every statistic downstream was
    then formally correct and substantively false.

    It also makes links immortal. A symbol removed from the prose survives
    forever, because the next run rediscovers it in the block written by the
    last one.
    """
    text = _FRONTMATTER.sub("", text)
    text = _MANAGED.sub("", text)
    text = _LEGACY_BLOCK.sub("", text)
    text = _GENERATED_LINE.sub("", text)
    return text


def strip_managed(text: str) -> str:
    """Remove the managed block, leaving everything a human wrote."""
    return _LEGACY_BLOCK.sub("", _MANAGED.sub("", text))


def candidates(text: str, symbols: Dict[str, str], min_len: int,
               stop: set) -> List[Tuple[str, str]]:
    """Symbols the note names, ranked by how deliberate the reference is.

    A name inside backticks is a decision; a bare word of the same spelling may
    be prose. Ranking before truncation matters — capping an alphabetically
    sorted list throws away the strongest evidence for the weakest.
    """
    ranked: Dict[str, str] = {}
    for span in _CODE_SPAN.findall(text):
        token = span.strip().rstrip("()").lstrip(".")
        if token in symbols:
            ranked[token] = "inline-code"
    for m in _SNAKE.findall(text):
        if m in ranked or m in stop or len(m) < min_len:
            continue
        if m in symbols:
            ranked[m] = "identifier"
    for m in _CAMEL.findall(text):
        if m in ranked or m.lower() in stop or len(m) < min_len:
            continue
        if m in symbols:
            ranked[m] = "identifier"
    order = {"inline-code": 0, "identifier": 1}
    return sorted(ranked.items(), key=lambda kv: (order[kv[1]], kv[0]))


def render_block(links: List[Tuple[str, str]], symbols: Dict[str, str]) -> str:
    body = "\n".join(f"- `{name}` — {symbols[name]}" for name, _why in links)
    return f"{_BLOCK_START}\n{_FORWARD_HEADING}\n\n{body}\n{_BLOCK_END}\n"


def apply_block(text: str, links: List[Tuple[str, str]],
                symbols: Dict[str, str]) -> str:
    """Always rebuilt from the current match; removed when nothing matches.

    The previous implementation only ran when there were hits, so a note whose
    last symbol left the prose kept its stale block indefinitely.
    """
    stripped = strip_managed(text)
    if not links:
        return stripped
    block = render_block(links, symbols)
    if stripped.startswith("---"):
        end = stripped.find("\n---", 3)
        cut = stripped.find("\n", end + 1) + 1 if end != -1 else 0
        return stripped[:cut] + "\n" + block + stripped[cut:]
    return block + "\n" + stripped


def write_atomic(path: str, content: str) -> None:
    tmp = path + ".tracelink.tmp"
    with open(tmp, "w") as fh:
        fh.write(content)
    os.replace(tmp, path)


def main() -> int:
    ap = argparse.ArgumentParser(description="Cross-link notes and code.")
    ap.add_argument("--vault", required=True)
    ap.add_argument("--symbols", required=True)
    ap.add_argument("--max-links", type=int, default=8,
                    help="cap per note, applied AFTER ranking (default 8)")
    ap.add_argument("--min-len", type=int, default=7,
                    help="minimum identifier length outside backticks (default 7)")
    ap.add_argument("--stopwords", default="", help="comma-separated extra names to ignore")
    ap.add_argument("--check", action="store_true",
                    help="report what would change, write nothing; exit 1 if stale")
    ap.add_argument("--explain", action="store_true",
                    help="print why each link was made")
    args = ap.parse_args()

    with open(args.symbols) as fh:
        payload = json.load(fh)
    symbols = payload.get("symbols") or payload
    stop = set(_DEFAULT_STOP) | {s.strip() for s in args.stopwords.split(",") if s.strip()}

    notes = sorted(
        p for p in os.listdir(args.vault)
        if p.endswith(".md") and p not in ("INDEX.md", "CODE-INDEX.md")
    )
    if not notes:
        print(f"no notes in {args.vault}")
        return 1

    backward: Dict[str, List[str]] = collections.defaultdict(list)
    scanned = with_matches = modified = total_links = 0

    for name in notes:
        path = os.path.join(args.vault, name)
        text = open(path, errors="replace").read()
        scanned += 1
        links = candidates(matchable(text), symbols, args.min_len, stop)[: args.max_links]
        if links:
            with_matches += 1
            total_links += len(links)
        new = apply_block(text, links, symbols)
        if new != text:
            modified += 1
            if not args.check:
                write_atomic(path, new)
        stem = os.path.splitext(name)[0]
        for sym, why in links:
            backward[sym].append(stem)
            if args.explain:
                print(f"{stem} -> {sym}\n    reason: {why}\n    destination: {symbols[sym]}")

    lines = [
        "# Code index — which notes mention which symbol",
        "",
        f"Generated from `{os.path.basename(args.symbols)}` "
        f"(backend: {payload.get('backend', 'unknown')}).",
        "",
        "Matching is lexical: it finds symbols the notes actually spell out.",
        "Frontmatter and generated blocks are excluded, so tracelink never",
        "matches its own output.",
        "",
        "| symbol | location | notes |",
        "|---|---|---|",
    ]
    for sym in sorted(backward, key=lambda s: (-len(set(backward[s])), s)):
        refs = " ".join(f"[[{n}]]" for n in sorted(set(backward[sym])))
        loc = str(symbols[sym]).replace("|", r"\|")
        lines.append(f"| `{sym}` | {loc} | {refs} |")
    index_text = "\n".join(lines) + "\n"

    index_path = os.path.join(args.vault, "CODE-INDEX.md")
    index_stale = (not os.path.exists(index_path)
                   or open(index_path, errors="replace").read() != index_text)
    if index_stale and not args.check:
        write_atomic(index_path, index_text)

    print(f"notes_scanned:      {scanned}")
    print(f"notes_with_matches: {with_matches}")
    print(f"notes_modified:     {modified}")
    print(f"symbols_linked:     {total_links}")
    print(f"distinct_symbols:   {len(backward)}")
    if args.check:
        stale = modified + (1 if index_stale else 0)
        print(f"check: {stale} file(s) would change")
        return 1 if stale else 0
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
